config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles

  resources :pictures

  get 'dashboard/index'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

	extend FriendlyId
	friendly_id :title, use: :slugged
	
	has_many :parts
	belongs_to :user
	has_attached_file :attachment, styles: {medium: "300x300", thumb: "100x100"}
  	validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/	


  	accepts_nested_attributes_for :parts, reject_if: proc { |attributes| attributes['part_title'].blank? }

	def self.top(limit)
		where(top: true).limit(limit)
	end
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :article
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	layout 'pictures', only: [:show]
	before_action :find_article, only: [:show]

  def index
  	@top_articles = Article.top(3)
		@recent_articles = Article.all
  end

	def new	
		@article = Article.new
		10.times {@article.parts.build}
	end

	def create
		@article = current_user.articles.new(article_params)

		if @article.save
			redirect_to root_url, notice: 'created article.'
		else
			render('new')
		end
	end

	def show
		@article = Article.friendly.find(params[:id])
		@parts = @article.parts.paginate(page: params[:page], per_page: 1)
	end

	private

		def find_article
			@article = Article.friendly.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :user_id, :attachment, :article_long, parts_attributes: [:part_title, :part_description])
		end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	layout 'pictures'

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)

		if @picture.save
			redirect_to root_url, notice: 'lol'
		else
			render('new')
		end
	end

	def show
		@picture = Picture.find(params[:id])
	end

	private

		def picture_params
			params.require(:picture).permit(:title)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def time_posted(time)
		time_ago_in_words(time)
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/articles/_articles.html.erb
<div class="row">
  <h3 class="text-center">top picks</h3>

  <% @top_articles.each do |article| %>
  <div class="large-4 columns">
    <div class="our-picks-container">
      <div class="our-picks-image">
        <%= image_tag article.attachment.url %>
      </div>

      <div class="our-picks-title">
        <span><%= article.title %></span>
        <hr></hr>
        <span class="editor"><%= link_to 'take me here', article_path(article) %></span>
      </div>
    </div>
  </div>
  <% end %>
</div>


<div class="spacing"></div>

<div class="recent-articles">
  <div class="row">
    <h3 class="text-center">recent articles</h3>
    <% @recent_articles.each do |article| %>
    <div class="large-4 columns">
      <div class="our-picks-container">
        <div class="our-picks-image">
          <%= image_tag article.attachment.url %>
        </div>

        <div class="our-picks-title">
          <span class="editor-black"><%= link_to article.title, article_path(article) %></span>
          <hr></hr>
          <span class="editor-black">posted <%= time_posted(article.created_at) %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render('articles') %>

app/views/articles/new.html.erb
<%= form_for @article, :url => articles_path, html: {multipart: true} do |f| %>
	<%= f.text_field :title %>
	<%= f.file_field :attachment %>
	<%= f.text_field :article_long %>
	<br><br>
	<%= f.fields_for :parts do |part| %>
		<%= part.text_field :part_title, placeholder: 'part title' %>
		<%= part.text_field :part_description, placeholder: 'part description' %>
	<% end %> 

	<%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<div class="row">
	<div class="article-holder">
		<div class="article-header">
			<%= image_tag @article.attachment.url %>
		</div>

		<div class="article-info">
			<div class="row">
				<div class="large-12 columns text-center">
					<h3><%= @article.title %></h3>
					<span>posted <%= time_posted(@article.created_at) %></span><br><br>
					<% @parts.each do |part| %>
						<% unless part.part_title.empty? %>
							<h3><%= part.part_title %></h3>
						<% end %>	
						
					<% end %>
				</div>
			</div>
			<div class="spacing"></div>
		</div>

		<div class="article-content">
			<div class="row">
				<div class="large-10 columns">
					<p>
						<% if @article.article_long.empty? %>
							<% @parts.each do |part| %>
								<%= part.part_description %>
							<% end %> 
						<% else %>
							<%= @article.article_long %>
						<% end %>
					</p>
					<div class="row">
						<div class="large-12 columns text-center">
						<%= will_paginate @parts %>
						</div>
					</div>
				</div>

				<div class="large-2 columns">
					<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
					<!-- responsive ad -->
					<ins class="adsbygoogle"
						 style="display:block"
						 data-ad-client="ca-pub-6039615735782011"
						 data-ad-slot="4475184882"
						 data-ad-format="auto">
					</ins>
					<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
					</script>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-header clearfix">
      <div class="row">
        <div class="small-6 medium-6 large-6 columns text-right">
          <span>logo</span>
        </div>

        <div class="small-6 medium-6 large-6 columns text-right">
          <nav>
            <a href="#">home</a>
            <a href="#">articles</a>
            <a href="#">streams</a>
          </nav>
        </div>
      </div>
    </div>

    <%= yield %>


  </body>
</html>

app/views/layouts/pictures.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-header clearfix">
      <div class="row">
        <div class="small-6 medium-6 large-6 columns">
          <span>logo</span>
        </div>

        <div class="small-6 medium-6 large-6 columns text-right">
          <nav>
            <a href="#">home</a>
            <a href="#">articles</a>
            <a href="#">streams</a>
          </nav>
        </div>
      </div>
    </div>


    <div class="sub-header">
    </div>

    <%= yield %>

  </body>
</html>

app/views/pictures/new.html.erb
<%= form_for @picture do |f| %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/pictures/show.html.erb
<div class="row">
	<div class="article-holder">
		<div class="article-header">
			<%= image_tag "gonf.png" %>
		</div>

		<div class="article-info">
			<div class="row">
				<div class="large-12 columns text-center">
					<h3><%= @picture.title %></h3>
					<span>posted 4 hours ago</span>
				</div>
			</div>
			<div class="spacing"></div>
		</div>

		<div class="article-content">
			<p>


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse finibus dui vitae elit tristique, non volutpat massa consectetur. Nulla facilisi. Aenean ultrices tristique mauris, nec ullamcorper lacus sodales blandit. Integer malesuada magna ac hendrerit sagittis. Sed sit amet felis a neque rhoncus suscipit nec non nisl. Suspendisse at nisi sollicitudin, posuere ipsum nec, facilisis metus. Curabitur scelerisque blandit egestas. Nam pretium tortor ac bibendum vulputate.
<br><br>
Curabitur rutrum congue nulla vel eleifend. Vestibulum efficitur auctor arcu vel dignissim. Sed molestie efficitur lorem vel ultrices. Nulla facilisi. Duis viverra, justo in elementum fringilla, nisi odio commodo sapien, nec commodo nibh est vitae nunc. Morbi a arcu lectus. Mauris mattis tristique elit, et accumsan neque efficitur ut. Etiam tincidunt nisi in auctor volutpat. Sed massa mauris, maximus ac placerat eget, pellentesque sit amet dui. Donec eget leo tempus, congue ligula ac, volutpat orci. Cras et ipsum est. Praesent auctor arcu aliquet, sodales leo in, aliquet nunc. Proin eleifend est vitae enim convallis ullamcorper. Ut at mi ligula. Pellentesque urna enim, placerat id dignissim eget, viverra dictum nisi. Nam malesuada dolor eget felis maximus, ac ultricies tellus consequat. 
			</p>
		</div>
	</div>
</div>